### ISSUE TITLE
[SCSS] directives & units invisible

### ISSUE THREAD

**Issue by VitorLuizC** [anoff/vscode-monokai-light#1]
`@directives` are just visible after typing brackets.

![](https://i.gyazo.com/ee2f085698ac941989d407f371fa9224.gif)

`rem` unit and, I think, other units are invisible.

![](https://i.gyazo.com/818dda0692f5995a1d1d5aef831969e3.gif)

**Comment by anoff** [comment]
I experienced similar issues with for other languages where incomplete syntax shows unreadable characters (white on white). Haven't bothered so far but I'll try to look into it.

As this is just a port of the theme file without anything vscode specific I wonder if vscode expects specific properties in the theme file that are not set.

You're welcome to tinker around with the theme as well, on your local installation the theme file should be located at `~/.vscode/extensions/anoff.theme-monokai-light-1.0.2`

**Comment by anoff** [comment]
Quick fix would be to remove [the lines that set `invalid`](https://github.com/anoff/vscode-monokai-light/blob/master/themes/Monokai%2520Light.tmTheme#L273)

Have to read up on why `invalid` and `invalid.deprecated` do not set the background property in vscode as expected.

Edit:
Seems like it's a [feature/known bug](https://github.com/Microsoft/vscode/issues/3429) in vscode.
Probably have to change those invalid settings then to go for a foreground color indicating a problem.
@VitorLuizC Do you have suggestions which color to pick for illegal syntax?

**Comment by VitorLuizC** [comment]
Sorry for the late answer. I think a gray color, like comments, or that default black would be great, It shows the code and let me know its a default text until I finish the directive.

**Comment by anoff** [comment]
update to `v1.0.3` to get black foreground for invalid syntax. I'll monitor the vsc issue in case they decide to bring in background colors and implement that
