### ISSUE TITLE
More scope selectors wanted

### ISSUE THREAD

**Issue by linsui** [anoff/vscode-monokai-light#4]
Thanks,this is just what I need. It will be better if you can add more scope selectors just like monokai :smile:

**Comment by anoff** [comment]
Hey @linsui what selectors are most important to you? Happy to extend the theme

**Comment by linsui** [comment]
I need these for markdown. Thanks again :smile:
- markup — this is for markup languages and generally applies to larger subsets of the text.
    - underline — underlined text.
    - link — this is for links, as a convenience this is derived from markup.underline so that if there is no theme rule which specifically targets markup.underline.link then it will inherit the underline style.
    - bold — bold text (text which is strong and similar should preferably be derived from this name).
    - heading — a section header. Optionally provide the heading level as the next element
    - italic — italic text 
    - list — list items.
    - numbered — numbered list items.
    - unnumbered — unnumbered list items.
    - quote — quoted (sometimes block quoted) text.
    - raw — text which is verbatim, e.g. code listings. Normally spell checking is disabled for markup.raw.
    - other — other markup constructs.
